---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.13.11
  install_strategy: once
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos/7
  - name: bento/amazonlinux-2

suites:
  - name: default
    run_list:
      - recipe[mondoo-test::default]
      - recipe[mondoo::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      mondoo:
        registration_token: changeme
