name 'mondoo'
maintainer 'Mondoo, Inc'
maintainer_email 'hello@mondoo.com'
license 'Apache-2.0'
description 'Installs and configures Mondoo Cient'
version '0.2.0'
chef_version '>= 14'
source_url 'https://github.com/mondoohq/chef-mondoo'
issues_url 'https://github.com/mondoohq/chef-mondoo/issues'

supports 'amazon'
supports 'ubuntu', '>= 16.04'
supports 'debian', '>= 9.0'
supports 'centos', '>= 6.0'
supports 'redhat', '>= 6.0'
supports 'scientific', '>= 7.0'