name: CI

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run Cookstyle
        run: chef exec cookstyle --display-cop-names --extra-details
        env:
          CHEF_LICENSE: accept-no-persist