name: chef supermaket
on:
  release:
    types: [published]

jobs:
  share:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1  
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - name: Release cookbook
        run: |
          gem install stove
          mkdir -p ~/.chef
          echo ${{ secrets.SUPERMARKET_PEM }} | base64 --decode > ~/.chef/key.pem
          stove login --username ${{ secrets.SUPERMARKET_USER }} --key ~/.chef/key.pem
          git status --porcelain
          stove --log-level debug --branch main
