---
name: Unit Testing

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec -f j -o tmp/rspec_results.json -f p
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@cf8af4a6ef5dfc5520025cc4fca8c979f1ca2fa4 # v7.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
        if: always()
